# Generated by Django 4.2.1 on 2023-05-12 12:52

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=140, validators=[post.models.validate_no_bad_words]),
        ),
    ]
