# Generated by Django 4.2.1 on 2023-05-12 12:52

from django.db import migrations
import useraccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favorite_color',
            field=useraccount.models.RBGcolorField(max_length=6, null=True),
        ),
    ]
