# Generated by Django 4.2.1 on 2023-05-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_useraccount_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photo'),
        ),
    ]
